### ISSUE TITLE
Doesn't work on Manjaro Linux

### ISSUE THREAD

**Issue by DissCent** [ysard/mintrayr#10]
So I have Thunderbird 60.0 installed, but I can't find the add-on on AMO, which is why I downloaded the XPI file manually and imported it into Thunderbird.

While the installation seems to work fine, there is neither a tray icon afterwards, nor a configuration option. The add-on seems to be loading according to this output:

```
console.log: "mintrayr - extension path: " "/home/philipp/.thunderbird/rj9xdcm6.default/extensions/mintray-reanimated@ysard.xpi"
console.log: "mintrayr - extraction path: " "/home/philipp/.thunderbird/rj9xdcm6.default/extensions/mintray-reanimated@ysard"
```

Any idea what might be wrong here?

EDIT: Also tried building the add-on myself (including the native lib) but that didn't help as well.

**Comment by ysard** [comment]
Hi, i'm still waiting a review on AMO. It has been 1 month...
Is your problem similar to #7 ?
If there is no error involving "loadManifestFromFile", it is another issue.

**Comment by DissCent** [comment]
Hi, thank you for your quick reply.

My full console output is this, so I don't think the issues are related:

```
[calBackendLoader] Using Thunderbird's builtin libical backend
console.log: "mintrayr - extension path: " "/home/philipp/.thunderbird/evtdzun1.default/extensions/mintray-reanimated@ysard.xpi"
console.log: "mintrayr - extraction path: " "/home/philipp/.thunderbird/evtdzun1.default/extensions/mintray-reanimated@ysard"
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
```

I'm actually not sure why there is also no settings button for the add-on - it just looks like that:

![screenshot_20181012_220154](https://user-images.githubusercontent.com/1782508/46891524-6f106200-ce6a-11e8-86c6-82839756b8a7.png)

(Deaktivieren = Disable, Entfernen = Delete)

**Comment by ysard** [comment]
Ok, In fact Thunderbird still accepts that the options of the addons are accessible from the drop-down menu of the main window: "Tools / Add-on Options"
As shown here:
https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57#Removed_and_changed_in_mozilla59
It should be the case on your installation.

**Comment by DissCent** [comment]
Ooh okay, I didn't know that, sorry!

So I accessed the settings now and closing thunderbird or minimizing it actually hides the window and doesn't exit the program, but there is still no tray icon which I can click to restore the window :/

Output is still the same (with 1.4.6).

**Comment by DissCent** [comment]
It seems to be KDE specific I guess. When entering my system tray settings, I can enable/disable the Thunderbird entry in the list while it is running, but it doesn't show.

**Comment by DissCent** [comment]
Oh well, never mind - I just restarted KDE and the icon is there now. Thanks and sorry for the trouble!
