### ISSUE TITLE
[Fedora, TB 60.2.1] Can't install from the file, "Disabling foreign installed add-on"

### ISSUE THREAD

**Issue by proninyaroslav** [ysard/mintrayr#12]
Hi. I tried to install add-on from the file, after installing it asks to restart app, but after rebooting, thunderbird disables it:

```
addons.xpi-utils WARN Disabling foreign installed add-on mintray-reanimated@ysard in app-profile
```

Then a window appears again that "another program wants to change thunderbird using the following add-on":

![2018-10-14 11-54-34](https://user-images.githubusercontent.com/7840559/46914546-e212f900-cf8e-11e8-9297-4125fd43ce05.png)

After allowing installation and restarting, thunderbird again disables add-on and shows this window after the next restart. It goes on forever.

**Comment by kolinger** [comment]
What is full "Location:"? It points to directory or .xpi file?

**Comment by proninyaroslav** [comment]
@kolinger yes, `mintray-reanimated@ysard.xpi` file in this folder.

**Comment by proninyaroslav** [comment]
1.4.6 version at the same problem.

**Comment by proninyaroslav** [comment]
It's work, thank you.
