### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by xbabyx** [ysard/mintrayr#25]
Hello,

How can I install this? I dragged the ".xpi" to "C:\Program Files (x86)\Mozilla Thunderbird\extensions " and restarted Thunderbird, it doesn't minimize if i click on - nor if i tab out, am i doing something wrong? ( also i think the XPI is being deleted after while)

I got windows 7, and latest updated version of thunderbird

Thanks.

**Comment by ysard** [comment]
Hi,
you have to install it from Thunderbird itself:

![image](https://user-images.githubusercontent.com/14988285/50049151-db634800-00dd-11e9-9738-44e1b5cf001f.png)

Regards

**Comment by xbabyx** [comment]
Perfect thank you a lot <3
Merci xD

**Comment by ysard** [comment]
De rien :p
