### ISSUE TITLE
Hide Thunderbird window by clicking on tray icon

### ISSUE THREAD

**Issue by vojtechsokol** [ysard/mintrayr#28]
Is it possible to add functionality from $SUBJECT?

I was using FireTray addon until it was made incompatible by tb v60+ and my usual use case was to click the tray icon to restore tb window, quick check if some interesting message appeared, and if not, click again to hide the window. Without this functionality, I have to either hit F9 or move the mouse and close the tb window.

Anyways great plugin, your work is really appreciated!

**Comment by ysard** [comment]
Hi, it should be fix in the next release ;)

**Comment by vojtechsokol** [comment]
Thanks, awesome :)
