### ISSUE TITLE
Windows 7 - Tray Context Menu

### ISSUE THREAD

**Issue by Pozix** [ysard/mintrayr#6]
Hello,

First of all thank you for reviving this extension.
The issue I have on Windows 7 is the tray context menu doesn't work IF TB is already minimized. It works correctly if it's not.

I saw the issue https://github.com/ysard/mintrayr/issues/3 was set to resolved but I don't know if you resolved the "intended behavior" as well or not.

**Comment by kolinger** [comment]
Seems like you have version before fix. I see that addons.thunderbird.net have 1.4.4, fix was made in 1.4.5. Maybe you are using version from thunderbird.net?

You can download current version from github - https://github.com/ysard/mintrayr/releases

**Comment by Pozix** [comment]
Yes, you're right. I was using the 1.4.4 from the addon page. My bad.
1.4.6 works fine.
