### ISSUE TITLE
Doesn't work in windows 10

### ISSUE THREAD

**Issue by Track77** [ysard/mintrayr#9]
All functions doesn't work.
Windows10x64
thunderbird x32 60.0 and 60.2.1 ( ukranian lang )

Also plugin creates the directory **Program%20Files%20(x86)\Mozilla%20Thunderbird\** => have to **Program Files (x86)\Mozilla Thunderbird** ( without **%20**)
![capture](https://user-images.githubusercontent.com/2233954/46530526-b7e07d80-c8a2-11e8-85e5-ddfc8874baf2.PNG)

**Comment by Track77** [comment]
Same issue in thunderbird x64

**Comment by Track77** [comment]
It starts work after i move installation directory to directory without whitespaces **ProgramData\MozillaThunderbird**

**Comment by ysard** [comment]
Hi, ok thank you for the issue;
the decoding of the URI of the installation folder is broken. I will try to fix that as soon as possible.

**Comment by ysard** [comment]
In fact that might be related to #5 ...
Which version do you use?
The version on addons.thunderbird is 1.4.4, this issue is fixed in 1.4.6 available on GitHub (https://github.com/ysard/mintrayr/releases).
If I update the version, it ends up at the end of the waiting list for reviews; for the moment it's been almost 3 weeks ... the delays are awful :/

**Comment by ysard** [comment]
Also don't hesitate to report the content of the console via Ctrl + Maj + J.

**Comment by Track77** [comment]
Thanks
I use the version 1.4.4.
I moved the Thunderbird to the **ProgramData\MozillaThunderbird** directory? so now can't test is version 1.4.6 fixes this.
Thanks for this useful plugin.
Have a great weekend!

**Comment by ysard** [comment]
Thank you, sorry for the problem.

You can move/change/create profiles by adding this parameter to the thunderbird command: "--ProfileManager".
More manually, there is a "profiles.ini" file in the folder (C:\Users\xxx\AppData\Roaming\Thunderbird\) that contains the path to the default profile on the system.
